# Generated by Django 4.2.20 on 2025-04-03 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please choose a title as short and accurate as possible, reflecting the main subject / context of the content. (max length: 100 characters)', max_length=100, unique=True, verbose_name='Title')),
                ('position', models.CharField(blank=True, choices=[('top_right', 'Top right'), ('top_left', 'Top left'), ('bottom_right', 'Bottom right'), ('bottom_left', 'Bottom left')], default='top_right', max_length=200, null=True, verbose_name='Position')),
                ('opacity', models.PositiveIntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Opacity')),
                ('allow_to_groups', models.ManyToManyField(blank=True, help_text='Select one or more groups who can manage and use this video dressing.', to='authentication.accessgroup', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'Video dressing',
                'verbose_name_plural': 'Video dressings',
            },
        ),
    ]
