# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dressing', '0001_initial'),
        ('podfile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressing',
            name='ending_credits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_credits', to='video.video', verbose_name='Ending credits'),
        ),
        migrations.AddField(
            model_name='dressing',
            name='opening_credits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_credits', to='video.video', verbose_name='Opening credits'),
        ),
        migrations.AddField(
            model_name='dressing',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owners_dressing', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
        migrations.AddField(
            model_name='dressing',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users_dressing', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='dressing',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos_dressing', to='video.video', verbose_name='Videos'),
        ),
        migrations.AddField(
            model_name='dressing',
            name='watermark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podfile.customimagemodel', verbose_name='Watermark'),
        ),
    ]
