# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Veuillez entrer un titre contenant entre 1 et 250 caractères.', max_length=250, verbose_name='Titre')),
                ('explanation', models.TextField(blank=True, default='', help_text='Veuillez choisir une explication.', verbose_name='Explication')),
                ('start_timestamp', models.PositiveIntegerField(help_text='L’heure de début de la réponse dans la vidéo (en secondes).', null=True, verbose_name='Horodatage de départ')),
                ('end_timestamp', models.PositiveIntegerField(help_text='L’heure de fin de la réponse dans la vidéo (en secondes).', null=True, verbose_name='Horodatage de fin')),
                ('choices', models.JSONField(default=dict, help_text="Les choix doivent ressembler à ceci\xa0: {'choix 1': true, 'choix 2': true, 'choix 3': false, …} | true pour le bon choix, false pour les mauvais choix.", verbose_name='Choix')),
            ],
            options={
                'verbose_name': 'Question à choix multiples',
                'verbose_name_plural': 'Questions à choix multiples',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_user_only', models.BooleanField(default=False, help_text='Veuillez choisir si ce quiz est réservé aux utilisateurs connectés ou non.', verbose_name='Utilisateur connecté uniquement')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Veuillez choisir si les réponses correctes seront affichées ou non.', verbose_name='Afficher les réponses correctes')),
                ('is_draft', models.BooleanField(default=False, help_text='Si la case est cochée, le quiz sera visible et accessible uniquement par vous et les propriétaires additionnels.', verbose_name='Brouillon')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Veuillez entrer un titre contenant entre 1 et 250 caractères.', max_length=250, verbose_name='Titre')),
                ('explanation', models.TextField(blank=True, default='', help_text='Veuillez choisir une explication.', verbose_name='Explication')),
                ('start_timestamp', models.PositiveIntegerField(help_text='L’heure de début de la réponse dans la vidéo (en secondes).', null=True, verbose_name='Horodatage de départ')),
                ('end_timestamp', models.PositiveIntegerField(help_text='L’heure de fin de la réponse dans la vidéo (en secondes).', null=True, verbose_name='Horodatage de fin')),
                ('is_true', models.BooleanField(default=True, help_text='Veuillez indiquer si la réponse est vraie ou fausse.', verbose_name='Is true')),
                ('quiz', models.ForeignKey(help_text='Veuillez choisir un quiz associé à la question.', on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question vrai/faux',
                'verbose_name_plural': 'Questions vrai/faux',
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Veuillez entrer un titre contenant entre 1 et 250 caractères.', max_length=250, verbose_name='Titre')),
                ('explanation', models.TextField(blank=True, default='', help_text='Veuillez choisir une explication.', verbose_name='Explication')),
                ('start_timestamp', models.PositiveIntegerField(help_text='L’heure de début de la réponse dans la vidéo (en secondes).', null=True, verbose_name='Horodatage de départ')),
                ('end_timestamp', models.PositiveIntegerField(help_text='L’heure de fin de la réponse dans la vidéo (en secondes).', null=True, verbose_name='Horodatage de fin')),
                ('choices', models.JSONField(default=dict, help_text="Les choix doivent ressembler à ceci\xa0: {'choix 1': true, 'choix 2': false, …} | true pour le bon choix, false pour les mauvais choix.", verbose_name='Choix')),
                ('quiz', models.ForeignKey(help_text='Veuillez choisir un quiz associé à la question.', on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question à choix unique',
                'verbose_name_plural': 'Questions à choix unique',
            },
        ),
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Veuillez entrer un titre contenant entre 1 et 250 caractères.', max_length=250, verbose_name='Titre')),
                ('explanation', models.TextField(blank=True, default='', help_text='Veuillez choisir une explication.', verbose_name='Explication')),
                ('start_timestamp', models.PositiveIntegerField(help_text='L’heure de début de la réponse dans la vidéo (en secondes).', null=True, verbose_name='Horodatage de départ')),
                ('end_timestamp', models.PositiveIntegerField(help_text='L’heure de fin de la réponse dans la vidéo (en secondes).', null=True, verbose_name='Horodatage de fin')),
                ('answer', models.CharField(default='', help_text='Veuillez choisir une réponse entre 1 et 250 caractères.', max_length=250, verbose_name='Réponse')),
                ('quiz', models.ForeignKey(help_text='Veuillez choisir un quiz associé à la question.', on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question à réponse courte',
                'verbose_name_plural': 'Questions à réponse courte',
            },
        ),
    ]
