# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='video',
            field=models.OneToOneField(help_text='Veuillez choisir une vidéo associée au quiz.', on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='Vidéo'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='quiz',
            field=models.ForeignKey(help_text='Veuillez choisir un quiz associé à la question.', on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('video',), name='unique_video'),
        ),
    ]
