# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorder', '0001_initial'),
        ('video', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='channel',
            field=models.ManyToManyField(blank=True, to='video.channel', verbose_name='Channels'),
        ),
        migrations.AddField(
            model_name='recorder',
            name='discipline',
            field=models.ManyToManyField(blank=True, help_text='The disciplines to which your content belongs.', to='video.discipline', verbose_name='Disciplines'),
        ),
        migrations.AddField(
            model_name='recorder',
            name='restrict_access_to_groups',
            field=models.ManyToManyField(blank=True, help_text='One or more groups who can access to this video', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='recorder',
            name='sites',
            field=models.ManyToManyField(to='sites.site'),
        ),
        migrations.AddField(
            model_name='recorder',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Separate tags with spaces, enclose the tags consist of several words in quotation marks.', to='recorder.tagulous_recorder_tags', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='recorder',
            name='theme',
            field=models.ManyToManyField(blank=True, help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', to='video.theme', verbose_name='Themes'),
        ),
        migrations.AddField(
            model_name='recorder',
            name='type',
            field=models.ForeignKey(help_text='Video type by default.', on_delete=django.db.models.deletion.CASCADE, to='video.type'),
        ),
        migrations.AddField(
            model_name='recorder',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Manager of this recorder. This manager will receive recorder emails and he will be the owner of the published videos. If no user is selected, this recorder will use manual assign system.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
