# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, editable=False, verbose_name='Date de création')),
                ('name', models.CharField(default='Liste de lecture', help_text='Please choose a title between 1 and 200 characters.', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', help_text='Veuillez choisir une description. Celle-ci est vide par défaut.', verbose_name='Description')),
                ('password', models.TextField(blank=True, default='', help_text='Veuillez choisir un mot de passe si cette playlist est protégée par un mot de passe.', verbose_name='Mot de passe')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('protected', 'Protégé par un mot de passe'), ('private', 'Privé')], default='private', help_text='Veuillez choisir un droit d’accès entre «\xa0public\xa0», «\xa0protégée par un mot de passe\xa0», «\xa0privée\xa0».', max_length=9, verbose_name='Droit d’accès')),
                ('autoplay', models.BooleanField(default=True, help_text='Veuillez choisir si cette playlist est en lecture automatique ou non.', verbose_name='Lecture automatique')),
                ('promoted', models.BooleanField(default=False, help_text='En sélectionnant ce paramètre, votre liste de lecture sera mise en avant dans la page listant les listes de lecture publiques promues. En revanche, si ce paramètre est désactivé, votre liste de lecture restera tout de même accessible par tous.<br>Pour une utilisation générale, il est conseillé de laisser ce paramètre désactivé.', verbose_name='Promue')),
                ('editable', models.BooleanField(default=True, help_text='Veuillez choisir si cette playlist est éditable ou non.', verbose_name='Éditable')),
                ('slug', models.SlugField(editable=False, help_text='Utilisé pour accéder à cette instance, le «\xa0titre court\xa0» est une étiquette formée uniquement de lettres (non accentuées), de chiffres, de l’underscore (barre de soulignement) et du tiret.', max_length=210, unique=True, verbose_name='titre court')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Liste de lecture',
                'verbose_name_plural': 'Listes de lecture',
                'ordering': ['name', 'owner', 'visibility', 'date_updated'],
                'get_latest_by': 'date_updated',
            },
        ),
        migrations.CreateModel(
            name='PlaylistContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date d’ajout')),
                ('rank', models.IntegerField(default=1, editable=False, verbose_name='Rang')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist', verbose_name='Liste de lecture')),
            ],
            options={
                'verbose_name': 'Élément de liste de lecture',
                'verbose_name_plural': 'Éléments de liste de lecture',
                'ordering': ['playlist', 'rank'],
                'get_latest_by': 'rank',
            },
        ),
    ]
