# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('playlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistcontent',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='Vidéo'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='additional_owners',
            field=models.ManyToManyField(blank=True, help_text='Vous pouvez ajouter des propriétaires additionnels à la playlist.', related_name='owners_playlists', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaires additionnels'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_playlist', to='sites.site', verbose_name='Site'),
        ),
        migrations.AddConstraint(
            model_name='playlistcontent',
            constraint=models.UniqueConstraint(fields=('playlist', 'video'), name='unique_playlist_video'),
        ),
    ]
