# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter a name that will allow you to easily find this recording.', max_length=250, verbose_name='Recording name')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Start date')),
                ('type', models.CharField(choices=[('bigbluebutton', 'Big Blue Button'), ('peertube', 'PeerTube'), ('video', 'Video file'), ('youtube', 'Youtube')], default='bigbluebutton', help_text='It is possible to manage recordings from Big Blue Button or another source delivering video files.', max_length=50, verbose_name='External record type')),
                ('source_url', models.CharField(default='', help_text='Please enter the address of the recording to download. This address must match the record type selected.', max_length=500, verbose_name='Address of the recording to download')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='Recording state')),
                ('owner', models.ForeignKey(blank=True, help_text='User who create this recording', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_external_recording', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_external_recording', to='sites.site', verbose_name='Site')),
                ('uploaded_to_pod_by', models.ForeignKey(blank=True, help_text='User who uploaded to Pod the video file', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader_external_recording', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'External recording',
                'verbose_name_plural': 'External recordings',
                'ordering': ('-start_at',),
                'get_latest_by': 'start_at',
            },
        ),
    ]
