# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('live', '0001_initial'),
        ('podfile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video.type', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_on_hold',
            field=models.ForeignKey(blank=True, help_text='This video will be displayed when there is no live stream.', null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='Video on hold'),
        ),
        migrations.AddField(
            model_name='event',
            name='videos',
            field=models.ManyToManyField(editable=False, related_name='event_videos', to='video.video'),
        ),
        migrations.AddField(
            model_name='event',
            name='viewers',
            field=models.ManyToManyField(editable=False, related_name='viewers_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='headband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podfile.customimagemodel', verbose_name='Headband'),
        ),
        migrations.AddField(
            model_name='building',
            name='sites',
            field=models.ManyToManyField(to='sites.site'),
        ),
        migrations.AddField(
            model_name='broadcaster',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='broadcaster',
            name='manage_groups',
            field=models.ManyToManyField(blank=True, help_text='Select one or more groups who can manage event to this broadcaster.', related_name='managegroups', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='broadcaster',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podfile.customimagemodel', verbose_name='Poster'),
        ),
    ]
