# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('completion', '0001_initial'),
        ('podfile', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='overlay',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podfile.customfilemodel', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='video'),
        ),
    ]
