# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('playlist', '0001_initial'),
        ('flatpages', '0002_flatpage_content_en_flatpage_content_fr_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='Channel',
            field=models.ForeignKey(blank=True, help_text='Select the channel you want to link with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='video.channel'),
        ),
        migrations.AddField(
            model_name='block',
            name='Playlist',
            field=models.ForeignKey(blank=True, help_text='Select the playlist you want to link with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist'),
        ),
        migrations.AddField(
            model_name='block',
            name='Theme',
            field=models.ForeignKey(blank=True, help_text='Select the theme you want to link with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='video.theme'),
        ),
        migrations.AddField(
            model_name='block',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Select the page of Pod you want to link with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='flatpages.flatpage'),
        ),
        migrations.AddField(
            model_name='block',
            name='sites',
            field=models.ManyToManyField(to='sites.site'),
        ),
    ]
