# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('code_name', models.CharField(max_length=250, unique=True)),
                ('auto_sync', models.BooleanField(default=False, help_text='Check if the access group must be synchronized on user connexion.', verbose_name='Auto synchronize')),
            ],
            options={
                'verbose_name': 'Access Groups',
                'verbose_name_plural': 'Access Groups',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Group site',
                'verbose_name_plural': 'Groups site',
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.CharField(choices=[('local', 'local'), ('CAS', 'CAS'), ('OIDC', 'OIDC'), ('Shibboleth', 'Shibboleth')], default='local', max_length=20)),
                ('affiliation', models.CharField(choices=[('student', 'student'), ('faculty', 'faculty'), ('staff', 'staff'), ('employee', 'employee'), ('member', 'member'), ('affiliate', 'affiliate'), ('alum', 'alum'), ('library-walk-in', 'library-walk-in'), ('researcher', 'researcher'), ('retired', 'retired'), ('emeritus', 'emeritus'), ('teacher', 'teacher'), ('registered-reader', 'registered-reader')], default='student', max_length=50)),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('hashkey', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('establishment', models.CharField(blank=True, choices=[('Etab_1', 'Etab_1'), ('Etab_2', 'Etab_2')], default='Etab_1', max_length=10, verbose_name='Establishment')),
                ('accepts_notifications', models.BooleanField(default=None, help_text='Receive push notifications on your devices.', null=True, verbose_name='Accept notifications')),
                ('accessgroups', models.ManyToManyField(blank=True, to='authentication.accessgroup')),
                ('sites', models.ManyToManyField(to='sites.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['user'],
            },
        ),
    ]
