# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sites', '0002_alter_domain_unique'),
        ('authentication', '0001_initial'),
        ('podfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='userpicture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podfile.customimagemodel', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='groupsite',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='groupsite',
            name='sites',
            field=models.ManyToManyField(to='sites.site'),
        ),
        migrations.AddField(
            model_name='accessgroup',
            name='sites',
            field=models.ManyToManyField(to='sites.site'),
        ),
        migrations.AddField(
            model_name='accessgroup',
            name='users',
            field=models.ManyToManyField(blank=True, to='authentication.owner'),
        ),
    ]
