# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIEnhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='La date et l’heure à laquelle l’enrichissement a été créé', verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='La date et l’heure à laquelle l’enrichissement a été mis à jour', verbose_name='Mis à jour le')),
                ('is_ready', models.BooleanField(default=False, help_text='Créer un enrichissement', verbose_name='Est prêt')),
                ('ai_enhancement_id_in_aristote', models.TextField(help_text='Entrez l’identifiant de l’enrichissement dans Aristote', verbose_name='ID d’enrichissement AI dans Aristote')),
            ],
            options={
                'verbose_name': 'Enrichissement AI',
                'verbose_name_plural': 'Enrichissements AI',
                'ordering': ['-created_at'],
                'get_latest_by': 'updated_at',
            },
        ),
    ]
