# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_enhancement', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aienhancement',
            name='video',
            field=models.OneToOneField(help_text='Sélectionnez la vidéo à améliorer avec l’IA', on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='Vidéo'),
        ),
    ]
