# Generated by Django 4.2.20 on 2025-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('enrichment', '0001_initial'),
        ('podfile', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentvtt',
            name='video',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='Vidéo'),
        ),
        migrations.AddField(
            model_name='enrichmentgroup',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Sélectionner un ou plusieurs groupes qui auront accès à la modification de l’enrichissement de la vidéo', to='auth.group', verbose_name='Groupes'),
        ),
        migrations.AddField(
            model_name='enrichmentgroup',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='Vidéo'),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Intégrer un document (PDF, texte, html)', null=True, on_delete=django.db.models.deletion.CASCADE, to='podfile.customfilemodel', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podfile.customimagemodel', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='vidéo'),
        ),
    ]
